### ISSUE TITLE
v2.17 segfaults

### ISSUE THREAD

**Issue by foutrelis** [axel-download-accelerator/axel#205]
Bisects to https://github.com/axel-download-accelerator/axel/commit/5aac471ad29f71e5d98a89533a6078f216a9777b. It looks like `axel->conf->num_connections` gets bumped to 1024 for a 100MB file even though I haven't used the `-n` switch.

The fix might be as simple as:

```
diff --git a/src/axel.c b/src/axel.c
index c6f901f..4b3f1c0 100644
--- a/src/axel.c
+++ b/src/axel.c
@@ -833,7 +833,7 @@ axel_divide(axel_t *axel)
 {
        /* Optimize the number of connections in case the file is small */
        size_t maxconns = axel->size / MIN_CHUNK_WORTH;
-       if (maxconns > axel->conf->num_connections)
+       if (maxconns < axel->conf->num_connections)
                axel->conf->num_connections = maxconns;
 
        /* Calculate each segment's size */
```

```
gdb --args ./src/axel https://speed.hetzner.de/100MB.bin
[...]
Initializing download: https://speed.hetzner.de/100MB.bin
File size: 104857600 bytes

Program received signal SIGSEGV, Segmentation fault.
0x000055555555a81a in axel_divide (axel=0x55555556b410) at axel.c:853
853			axel->conn[i].currentbyte = seg_len * i;
(gdb) p i
$1 = 87
(gdb) p axel->conf->num_connections
$2 = 1024
(gdb) bt
#0  0x000055555555a81a in axel_divide (axel=0x55555556b410) at axel.c:853
#1  0x00005555555586e4 in axel_open (axel=0x55555556b410) at axel.c:317
#2  0x0000555555561bb4 in main (argc=2, argv=0x7fffffffe778) at text.c:379
```

**Comment by ismaell** [comment]
Thanks!
